version: '3'

services:
  sut:
    environment:
      MONGO_INITDB_URL: mongo
    build: 
      context: .
      dockerfile: test/Dockerfile
    command: go test ./...
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 3306:3306
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123